server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rpadb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8#jdbc:h2:tcp://localhost/~/rpa #
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver #
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      # show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace